spring:
  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,slf4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: non_null
  profiles:
    active:
      - common
      - private #此配置文件保存了一些敏感信息(数据库配置和ssl配置等)，未开源
  session:
    store-type: jdbc
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations:
    - icu/fordring/voter/mapper/*.xml
  type-aliases-package: icu.fordring.voter.pojo
logging:
  level:
    # root日志以WARN级别输出
    root: info
server:
  ssl:
    protocol: TLS
    key-alias: ${app.ssl.key-alias}
    key-store: ${app.ssl.key-store}
    key-store-password: ${app.ssl.key-store-password}
    key-store-type: ${app.ssl.key-store-type}
  port: 443
